/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    media: Media;
    projects: Project;
    'project-categories': ProjectCategory;
    technologies: Technology;
    skills: Skill;
    'skill-categories': SkillCategory;
    experiences: Experience;
    education: Education;
    certifications: Certification;
    services: Service;
    testimonials: Testimonial;
    'contact-messages': ContactMessage;
    posts: Post;
    'post-categories': PostCategory;
    tags: Tag;
    authors: Author;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    'skill-categories': SkillCategoriesSelect<false> | SkillCategoriesSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name: string;
  avatar?: (number | null) | Media;
  role: 'super-admin' | 'admin' | 'editor' | 'viewer';
  isActive?: boolean | null;
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  description?: string | null;
  folder?: ('general' | 'projects' | 'profile' | 'certifications' | 'blog' | 'videos' | 'documents') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  thumbnail?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Paste a YouTube, Vimeo, or direct .mp4/.webm link. Preferred for large demos.
   */
  videoUrl?: string | null;
  /**
   * Optional MP4/WebM upload (keep under ~50MB locally; use Blob in production).
   */
  videoFile?: (number | null) | Media;
  /**
   * Add more demos / walkthroughs for this project.
   */
  videos?:
    | {
        title?: string | null;
        url?: string | null;
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  problemStatement?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  businessChallenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  proposedSolution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  systemArchitecture?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  databaseArchitecture?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  keyModules?:
    | {
        module: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  responsibilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  developmentProcess?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  technicalImplementation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challenges?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challengeSolutions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  securityImplementation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  performanceImprovements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  results?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  measurableOutcomes?:
    | {
        outcome: string;
        id?: string | null;
      }[]
    | null;
  lessonsLearned?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  futureImprovements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categories?: (number | ProjectCategory)[] | null;
  technologies?: (number | Technology)[] | null;
  projectType?:
    ('personal' | 'professional' | 'client' | 'company' | 'academic' | 'open-source' | 'research' | 'internal') | null;
  projectStatus?: ('completed' | 'in-progress' | 'maintenance' | 'planned' | 'concept' | 'archived' | 'private') | null;
  clientName?: string | null;
  companyName?: string | null;
  startDate?: string | null;
  completionDate?: string | null;
  demoUrl?: string | null;
  githubUrl?: string | null;
  repositoryVisibility?: ('public' | 'private' | 'none') | null;
  documentationUrl?: string | null;
  caseStudyUrl?: string | null;
  relatedProjects?: (number | Project)[] | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (number | null) | Media;
  canonicalUrl?: string | null;
  noIndex?: boolean | null;
  featured?: boolean | null;
  displayOrder?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Optional Lucide icon name
   */
  icon?: string | null;
  image?: (number | null) | Media;
  parent?: (number | null) | ProjectCategory;
  displayOrder?: number | null;
  isActive?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  icon?: string | null;
  category?:
    | (
        | 'programming-language'
        | 'framework'
        | 'database'
        | 'cloud'
        | 'ai'
        | 'erp'
        | 'devops'
        | 'frontend'
        | 'backend'
        | 'data-science'
        | 'automation'
        | 'other'
      )
    | null;
  description?: string | null;
  officialUrl?: string | null;
  displayOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  name: string;
  slug: string;
  category: number | SkillCategory;
  icon?: string | null;
  logo?: (number | null) | Media;
  proficiency: 'expert' | 'advanced' | 'intermediate' | 'working-knowledge' | 'familiar';
  yearsOfExperience?: number | null;
  description?: string | null;
  /**
   * Optional presentation-only percentage
   */
  proficiencyPercent?: number | null;
  relatedTechnologies?: (number | Technology)[] | null;
  featured?: boolean | null;
  displayOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-categories".
 */
export interface SkillCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  icon?: string | null;
  displayOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  companyName: string;
  companyLogo?: (number | null) | Media;
  companyUrl?: string | null;
  jobTitle: string;
  employmentType?:
    ('full-time' | 'part-time' | 'contract' | 'freelance' | 'consulting' | 'internship' | 'self-employed') | null;
  location?: string | null;
  workMode?: ('on-site' | 'remote' | 'hybrid') | null;
  startDate: string;
  endDate?: string | null;
  currentlyWorking?: boolean | null;
  summary?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  responsibilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  achievements?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  projectsHandled?: (number | Project)[] | null;
  technologies?: (number | Technology)[] | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: number;
  institution: string;
  institutionLogo?: (number | null) | Media;
  degree: string;
  fieldOfStudy?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  currentlyStudying?: boolean | null;
  grade?: string | null;
  location?: string | null;
  description?: string | null;
  achievements?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  activities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  title: string;
  issuer: string;
  organizationLogo?: (number | null) | Media;
  certificateImage?: (number | null) | Media;
  certificatePdf?: (number | null) | Media;
  issueDate?: string | null;
  expiryDate?: string | null;
  doesNotExpire?: boolean | null;
  credentialId?: string | null;
  verificationUrl?: string | null;
  description?: string | null;
  skillsCovered?: (number | Skill)[] | null;
  featured?: boolean | null;
  displayOrder?: number | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon?: string | null;
  coverImage?: (number | null) | Media;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  technologies?: (number | Technology)[] | null;
  processSteps?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  startingPriceText?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  featured?: boolean | null;
  displayOrder?: number | null;
  isActive?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  clientPosition?: string | null;
  company?: string | null;
  clientImage?: (number | null) | Media;
  testimonial: string;
  rating?: number | null;
  relatedProject?: (number | null) | Project;
  featured?: boolean | null;
  approved?: boolean | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  subject: string;
  service?: (number | null) | Service;
  budget?: string | null;
  preferredContactMethod?: ('email' | 'phone' | 'whatsapp') | null;
  message: string;
  status?: ('new' | 'read' | 'in-progress' | 'replied' | 'converted' | 'archived' | 'spam') | null;
  sourcePage?: string | null;
  ipHash?: string | null;
  userAgent?: string | null;
  readAt?: string | null;
  repliedAt?: string | null;
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  author?: (number | null) | Author;
  category?: (number | null) | PostCategory;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  /**
   * Minutes (auto-estimated if empty)
   */
  readingTime?: number | null;
  featured?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (number | null) | Media;
  canonicalUrl?: string | null;
  noIndex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  role?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: number | ProjectCategory;
      } | null)
    | ({
        relationTo: 'technologies';
        value: number | Technology;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'skill-categories';
        value: number | SkillCategory;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  isActive?: T;
  lastLogin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  description?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  fullDescription?: T;
  coverImage?: T;
  thumbnail?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  videoUrl?: T;
  videoFile?: T;
  videos?:
    | T
    | {
        title?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  problemStatement?: T;
  businessChallenge?: T;
  proposedSolution?: T;
  systemArchitecture?: T;
  databaseArchitecture?: T;
  keyModules?:
    | T
    | {
        module?: T;
        id?: T;
      };
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  developmentProcess?: T;
  technicalImplementation?: T;
  challenges?: T;
  challengeSolutions?: T;
  securityImplementation?: T;
  performanceImprovements?: T;
  results?: T;
  measurableOutcomes?:
    | T
    | {
        outcome?: T;
        id?: T;
      };
  lessonsLearned?: T;
  futureImprovements?: T;
  categories?: T;
  technologies?: T;
  projectType?: T;
  projectStatus?: T;
  clientName?: T;
  companyName?: T;
  startDate?: T;
  completionDate?: T;
  demoUrl?: T;
  githubUrl?: T;
  repositoryVisibility?: T;
  documentationUrl?: T;
  caseStudyUrl?: T;
  relatedProjects?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  canonicalUrl?: T;
  noIndex?: T;
  featured?: T;
  displayOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  image?: T;
  parent?: T;
  displayOrder?: T;
  isActive?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  icon?: T;
  category?: T;
  description?: T;
  officialUrl?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  icon?: T;
  logo?: T;
  proficiency?: T;
  yearsOfExperience?: T;
  description?: T;
  proficiencyPercent?: T;
  relatedTechnologies?: T;
  featured?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-categories_select".
 */
export interface SkillCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  companyName?: T;
  companyLogo?: T;
  companyUrl?: T;
  jobTitle?: T;
  employmentType?: T;
  location?: T;
  workMode?: T;
  startDate?: T;
  endDate?: T;
  currentlyWorking?: T;
  summary?: T;
  fullDescription?: T;
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  achievements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  projectsHandled?: T;
  technologies?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  institution?: T;
  institutionLogo?: T;
  degree?: T;
  fieldOfStudy?: T;
  startDate?: T;
  endDate?: T;
  currentlyStudying?: T;
  grade?: T;
  location?: T;
  description?: T;
  achievements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  activities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  title?: T;
  issuer?: T;
  organizationLogo?: T;
  certificateImage?: T;
  certificatePdf?: T;
  issueDate?: T;
  expiryDate?: T;
  doesNotExpire?: T;
  credentialId?: T;
  verificationUrl?: T;
  description?: T;
  skillsCovered?: T;
  featured?: T;
  displayOrder?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  fullDescription?: T;
  icon?: T;
  coverImage?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  technologies?: T;
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  startingPriceText?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  featured?: T;
  displayOrder?: T;
  isActive?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  clientPosition?: T;
  company?: T;
  clientImage?: T;
  testimonial?: T;
  rating?: T;
  relatedProject?: T;
  featured?: T;
  approved?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  service?: T;
  budget?: T;
  preferredContactMethod?: T;
  message?: T;
  status?: T;
  sourcePage?: T;
  ipHash?: T;
  userAgent?: T;
  readAt?: T;
  repliedAt?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  author?: T;
  category?: T;
  tags?: T;
  publishedAt?: T;
  readingTime?: T;
  featured?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  canonicalUrl?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteTagline?: string | null;
  logo?: (number | null) | Media;
  darkLogo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contactEmail?: string | null;
  businessEmail?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  location?: string | null;
  resume?: (number | null) | Media;
  githubUrl?: string | null;
  linkedinUrl?: string | null;
  kaggleUrl?: string | null;
  facebookUrl?: string | null;
  instagramUrl?: string | null;
  youtubeUrl?: string | null;
  xUrl?: string | null;
  defaultSeoTitle?: string | null;
  defaultSeoDescription?: string | null;
  defaultSeoImage?: (number | null) | Media;
  footerText?: string | null;
  copyrightText?: string | null;
  analyticsId?: string | null;
  maintenanceMode?: boolean | null;
  blogEnabled?: boolean | null;
  testimonialsEnabled?: boolean | null;
  contactFormEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  fullName?: string | null;
  professionalTitle?: string | null;
  tagline?: string | null;
  introduction?: string | null;
  profileImage?: (number | null) | Media;
  backgroundImage?: (number | null) | Media;
  availabilityStatus?: string | null;
  primaryCtaLabel?: string | null;
  primaryCtaUrl?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaUrl?: string | null;
  showResumeButton?: boolean | null;
  highlights?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  featuredProjectsHeading?: string | null;
  featuredProjectsIntro?: string | null;
  featuredProjects?: (number | Project)[] | null;
  skillsHeading?: string | null;
  featuredSkillCategories?: (number | SkillCategory)[] | null;
  experienceHeading?: string | null;
  servicesHeading?: string | null;
  featuredServices?: (number | Service)[] | null;
  certificationsHeading?: string | null;
  featuredCertifications?: (number | Certification)[] | null;
  testimonialsHeading?: string | null;
  contactCtaHeading?: string | null;
  contactCtaText?: string | null;
  contactCtaLabel?: string | null;
  contactCtaUrl?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  pageHeading?: string | null;
  biography?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  careerSummary?: string | null;
  professionalObjectives?: string | null;
  workPhilosophy?: string | null;
  currentRole?: string | null;
  location?: string | null;
  availability?: string | null;
  profileImage?: (number | null) | Media;
  resume?: (number | null) | Media;
  languages?:
    | {
        language: string;
        level?: string | null;
        id?: string | null;
      }[]
    | null;
  values?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  coreCompetencies?: (number | Skill)[] | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerItems?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerItems?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  showCta?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  logo?: T;
  darkLogo?: T;
  favicon?: T;
  contactEmail?: T;
  businessEmail?: T;
  phone?: T;
  whatsapp?: T;
  location?: T;
  resume?: T;
  githubUrl?: T;
  linkedinUrl?: T;
  kaggleUrl?: T;
  facebookUrl?: T;
  instagramUrl?: T;
  youtubeUrl?: T;
  xUrl?: T;
  defaultSeoTitle?: T;
  defaultSeoDescription?: T;
  defaultSeoImage?: T;
  footerText?: T;
  copyrightText?: T;
  analyticsId?: T;
  maintenanceMode?: T;
  blogEnabled?: T;
  testimonialsEnabled?: T;
  contactFormEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  fullName?: T;
  professionalTitle?: T;
  tagline?: T;
  introduction?: T;
  profileImage?: T;
  backgroundImage?: T;
  availabilityStatus?: T;
  primaryCtaLabel?: T;
  primaryCtaUrl?: T;
  secondaryCtaLabel?: T;
  secondaryCtaUrl?: T;
  showResumeButton?: T;
  highlights?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  featuredProjectsHeading?: T;
  featuredProjectsIntro?: T;
  featuredProjects?: T;
  skillsHeading?: T;
  featuredSkillCategories?: T;
  experienceHeading?: T;
  servicesHeading?: T;
  featuredServices?: T;
  certificationsHeading?: T;
  featuredCertifications?: T;
  testimonialsHeading?: T;
  contactCtaHeading?: T;
  contactCtaText?: T;
  contactCtaLabel?: T;
  contactCtaUrl?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  pageHeading?: T;
  biography?: T;
  careerSummary?: T;
  professionalObjectives?: T;
  workPhilosophy?: T;
  currentRole?: T;
  location?: T;
  availability?: T;
  profileImage?: T;
  resume?: T;
  languages?:
    | T
    | {
        language?: T;
        level?: T;
        id?: T;
      };
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  coreCompetencies?: T;
  seoTitle?: T;
  seoDescription?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerItems?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        visible?: T;
        id?: T;
      };
  footerItems?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  showCta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}